language: perl
sudo: required
dist: trusty

addons:
  sonarqube: true

before_install:
- cpanm --notest Perl::Tidy
- cpanm --notest Test::Code::TidyAll
- cpanm --notest Test::Perl::Critic

perl:
- '5.20'

script:
- sonar-scanner -e -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN

env:
  global:
    secure: JsxP0aQm8P/Om8tDku7e0Nnf51pKd7SfeAaSQSsp5iduoLF/MGgocIpeBMbw14/3hipchCzwJPCFalEgNVByT3ChvUR3WvLfDkoTNbxPtZpN9167GlHKAj3zamdlD7AJwcf4+wBRXAaSBp1xzO53dHgJzJTVZsPWUpTE4hZfy2bceeDhjWYL5xaAyI/1aOlxHRDmPb+o9S7QzcxP0eJdj9hQpBTfuebrUm43MMwsbWvMm+oYGk65czqYnd0qTMp3zNnh6wdwb/PRrCn4r3R4J1E/4MP0ftcyzyT0orn5BiE3MZbCWVYWCwbTibpMPqZdTaE40E7M4wyz8bCXRA83mRJ0VJgmOZJ2gmnzjl2wXDRz8cLtmYKkFz5+j40cbBPVPLNzWaQsFHt78gzdJsYDwCId3hXJy5OUGBBg88LjeAL/9KpvjCv0+73oY6PyZnpMdm/H+E8h3bPRDVGg0e8GTxhvir2dTHw5X/ZdxdUKNt54lPluelQ8ZKYGSu9P4KVWwBKqqNEPce3lCRGWw6YaQyiBfWuC1kg+uvh9iIogEFGGLpZ0ERYX1JhgdvaK+/qfWpy3Vikou2W3EoTqi4dgc9+DonRkwKx+XibdD5Y1yNkLWvtiBm4u+qBS9Q7lR8TrOh5/FDRQI/q/+dTzwKXzC6BXqz6QGdy/r+/t9IizpRQ=
